{
  "download_path": "/Users/diya/Desktop/Selenium/",
  "chromedriver_path": "/Users/diya/Desktop/Selenium/chromedriver",
  "date": "2025-03-04",    # Date in the format YYYY-MM-DD
  "success_failed_path": "/Users/diya/Desktop/Selenium/gov_sesh/"
}