{
  "download_path": "/Users/diya/Desktop/Selenium/",
  "chromedriver_path": "/Users/diya/Desktop/Selenium/chromedriver",
  "start_date": "2025-03-03",
  "end_date": "2025-03-03",
  "home_url": "https://sg001-harmony.sliq.net/00283/Harmony/en/View/EventListView/20250310/-1",
  "success_failed_path": "/Users/diya/Desktop/Selenium/gov_sesh/"
}